version: "3.3"

services:
  user:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: user
    command:
      [
        "npm",
        "run",
        "start",
      ]
    restart: always
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    networks:
      - capju
    env_file:
      - .env

networks:
  capju:
    external: true
