version: '3.3'

services:
  process_management:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: process_management
    command: [
      './wait-for-it.sh',
      'db:5432',
      '--',
      'npm',
      'run',
      'start',
      ]
    restart: always
    volumes:
      - ./:/app
    ports:
      - 8082:8082
    networks:
      - capju
    env_file:
      - .env

networks:
  capju:
    external: true
