version: "3.3"

services:
  process_management:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: process_management
    entrypoint: ["/bin/sh", "-c", "./entrypoint.sh"]
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8082:8082
    networks:
      - capju
    env_file:
      - .env

networks:
  capju:
    external: true
