version: '3.3'

services:
  user:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: user
    command: ['/bin/sh', '-c', 'npm start']
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8080:8080
    networks:
      - capju
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo

networks:
  capju:
    external: true
